### ISSUE TITLE
A command that generates the settings for currently installed extensions.

### ISSUE THREAD

**Issue by hashhar** [webstp/extension-manager#7]
This command will generate a `settings.json` compatible snippet (basically an array of installed extensions) which can then be simply pasted into the settings.json. It is very difficult to manually update the list every time.

I can send you a PR within the next week.

**Comment by DavidBabel** [comment]
Any news on this ?

**Comment by hashhar** [comment]
@DavidBabel Really sorry. I got really busy. I can start working on it later during the day. Check tomorrow sometime.

**Comment by hashhar** [comment]
Implemented. I'll push a PR.

ping @webstp. I updated the project to TypeScript 2 and did the best monkey patching I've ever done. Could you take a look at this.

**Comment by webstp** [comment]
Commented on the PR. Are people still using this extension even though VSCode now support recommended extensions?

**Comment by hashhar** [comment]
Hmmmm, it never occurred to me that we can use it that way. Thanks for giving me the idea. In the meantime the extension served me well.
